package com.example.restservicedemo.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.example.restservicedemo.domain.Car;
import com.example.restservicedemo.domain.Person;

public class PersonManager {

	private Connection connection;

	private static final String URL = "jdbc:hsqldb:hsql://localhost/workdb";
	private static final String CREATE_TABLE_PERSON = "CREATE TABLE Person(p_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY(start with 1), name varchar(20), yob integer)";

	private PreparedStatement addPersonStmt;
	private PreparedStatement removePersonStmt;

	private PreparedStatement deleteAllPersonsStmt;
	private PreparedStatement getAllPersonsStmt;
	private PreparedStatement getPersonByFirstNameStmt;
	private PreparedStatement getPersonByIdStmt;
	private PreparedStatement dropTable;

	private PreparedStatement getAllPersonsWithCarsStmt;


	private Statement statement;

	public PersonManager() {
		try {
			connection = DriverManager.getConnection(URL);
			statement = connection.createStatement();

			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Person".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if (!tableExists)
				statement.executeUpdate(CREATE_TABLE_PERSON);


			addPersonStmt = connection.prepareStatement(
					"INSERT INTO Person (name, yob) VALUES (?, ?)");
			removePersonStmt = connection.prepareStatement(
					"DELETE FROM Person where p_id = ?");
			deleteAllPersonsStmt = connection.prepareStatement(
					"DELETE FROM Person");
			getAllPersonsStmt = connection.prepareStatement(
					"SELECT p_id, name, yob FROM Person");
			getPersonByFirstNameStmt = connection.prepareStatement(
					"SELECT p_id, name, yob FROM Person where name = ?");			
			getPersonByIdStmt = connection.prepareStatement(
					"SELECT p_id, name, yob FROM Person where p_id = ?");
			getAllPersonsWithCarsStmt = connection.prepareStatement(
					"SELECT p_id, name, yob, c_id, model, yop, owner_id FROM Person JOIN Car ON owner_id = p_id");
			dropTable = connection.prepareCall(
					"DROP TABLE Person"
			);

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	Connection getConnection() {
		return connection;
	}

	public void clearPersons() {
		try {
			deleteAllPersonsStmt.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public int addPerson(Person person) {
		int count = 0;
		try {
			addPersonStmt.setString(1, person.getFirstName());
			addPersonStmt.setInt(2, person.getYob());

			count = addPersonStmt.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return count;
	}

	public void dropTable() throws SQLException {
		try {
			connection = DriverManager.getConnection(URL);
			statement = connection.createStatement();

			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;

			rs = connection.getMetaData().getTables(null, null, null, null);
			tableExists = false;
			while (rs.next()) {
				if ("Person".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}
			if (tableExists)
				dropTable.executeQuery();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public int removePerson(long id) {
		int count = 0;
		try {
			removePersonStmt.setLong(1, id);

			count = removePersonStmt.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return count;
	}

	public List<Person> getAllPersons() {
		List<Person> persons = new ArrayList<Person>();

		try {
			ResultSet rs = getAllPersonsStmt.executeQuery();

			while (rs.next()) {
				Person p = new Person();
				p.setId(rs.getInt("p_id"));
				p.setFirstName(rs.getString("name"));
				p.setYob(rs.getInt("yob"));
				persons.add(p);
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return persons;
	}
	public Person getPersonFromFirstName(String name) {
		Person p = new Person();
		try {
			getPersonByFirstNameStmt.setString(1, name);
			ResultSet rs = getPersonByFirstNameStmt.executeQuery();

			while (rs.next()) {
				p.setId(rs.getInt("p_id"));
				p.setFirstName(rs.getString("name"));
				p.setYob(rs.getInt("yob"));
				break;
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}

		return p;
	}
	public Person getPerson(int id) {
		Person p = new Person();
		try {
			getPersonByIdStmt.setInt(1, id);
			ResultSet rs = getPersonByIdStmt.executeQuery();

			while (rs.next()) {
				p.setId(rs.getInt("p_id"));
				p.setFirstName(rs.getString("name"));
				p.setYob(rs.getInt("yob"));
				break;
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}

		return p;
	}

	public Map<Person, List<Car>> getPersonWithCar() {

		List<Car> cars = new ArrayList<Car>();

		Map<Person, List<Car>> result = new HashMap<>();

		try {
			ResultSet rs = getAllPersonsWithCarsStmt.executeQuery();

			while (rs.next()) {

				Person p = new Person();

				p.setId(rs.getInt("p_id"));
				p.setFirstName(rs.getString("name"));
				p.setYob(rs.getInt("yob"));

				Car c = new Car();
				c.setId(rs.getInt("c_id"));
				c.setModel(rs.getString("model"));
				c.setYop(rs.getInt("yop"));

				c.setOwner(p);

				if (result.containsKey(p)) {
					cars = result.get(p);
					cars.add(c);
				} else {
					cars = new ArrayList<>();
					cars.add(c);
					result.put(p, cars);
				}

			}

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return result;
	}
}